---

- name: "CREATE THE VIRTUAL ROUTERS"
  panos_virtual_router:
    ip_address: '{{ ansible_host }}'
    username: '{{ username }}'
    password: '{{ password }}'
    name: '{{ item }}'
    state: "present"
  with_items: "{{ cm_virtual_router }}"
  when: "cm_virtual_router is defined"

- name: "CREATE THE INTERFACES AND PROPERTIES OF SAID INTERFACE"
  panos_interface:
    ip_address: '{{ ansible_host }}'
    username: '{{ username }}'
    password: '{{ password }}'
    operation: "{{ item['operation'] }}"
    if_name: "{{ item['name'] }}"
    ip: "{{ item['ip'] | default(None) | item_to_list or omit }}"
    zone_name: "{{ item['zone'] }}"
    vr_name: "{{ item['virtual_router'] }}"
    enable_dhcp: "{{ item['dhcp'] | default(false) }}"
    create_default_route: "{{ item['create_default_route'] | default(false) }}"
    management_profile: "{{ item['mgmt_profile'] | default(omit) }}"
    commit: "false"
  with_items: "{{ cm_interface | selectattr('name' , 'match', pattern='^ethernet') | list }}"
  ignore_errors: true
  when: "cm_interface is defined"

- name: "CREATE THE INTERFACES AND PROPERTIES OF SAID INTERFACE"
  panos_interface:
    ip_address: '{{ ansible_host }}'
    username: '{{ username }}'
    password: '{{ password }}'
    operation: "add"
    if_name: "{{ item['name'] }}"
    ip: "{{ item['ip'] | default(None) | item_to_list or omit }}"
    zone_name: "{{ item['zone'] }}"
    vr_name: "{{ item['virtual_router'] }}"
    enable_dhcp: "{{ item['dhcp'] | default(false) }}"
    create_default_route: "{{ item['create_default_route'] | default(false) }}"
    management_profile: "{{ item['mgmt_profile'] | default(omit) }}"
    commit: "false"
  with_items: "{{ cm_interface | selectattr('name' , 'match', pattern='^ethernet') | list }}"
  ignore_errors: true
  when: "cm_interface is defined"
