---

- name: Import Iron Skillet for AWS
  panos_import:
    ip_address: '{{ ansible_host }}'
    username: '{{ username }}'
    password: '{{ password }}'
    url: "https://raw.githubusercontent.com/PaloAltoNetworks/iron-skillet/panos_v8.1/loadable_configs/sample-cloud-AWS/panos/iron_skillet_panos_full.xml"
    category: "configuration"
    validate_certs: false
  register: result

- name: Load Iron Skillet for AWS
  panos_loadcfg:
    ip_address: "{{ ansible_host }}"
    username: "{{ username }}"
    password: "{{ password }}"
    file: "{{result.filename}}"