---

- name: Generate IPSec Profiles on Firewalls
  panos_ipsec_profile:
    ip_address: '{{ ansible_host }}'
    username: '{{ username }}'
    password: '{{ password }}'
    state: "{{ item['state'] | default('present') }}"
    name: "{{ item['name'] }}"
    encryption: "{{ item['encryption'] | default(omit) }}"
    authentication: "{{ item['authentication'] | default(omit) }}"
    dhgroup: "{{ item['dhgroup'] | default(omit) }}"
    lifetime_hrs: "{{ item['lifetime_hrs'] | default(omit) }}"
    commit: "{{ item['commit'] | default('false') }}"
  with_items: "{{ cm_panos_ipsec_profile }}"
  when: "cm_panos_ipsec_profile is defined"

- name: Add IKE crypto config to the firewall
  panos_ike_crypto_profile:
    ip_address: '{{ ansible_host }}'
    username: '{{ username }}'
    password: '{{ password }}'
    state: "{{ item['state'] | default('present') }}"
    name: "{{ item['name'] }}"
    dhgroup: "{{ item['dhgroup'] | default(omit) }}"
    authentication: "{{ item['authentication'] | default(omit) }}"
    encryption: "{{ item['encryption'] | default(omit) }}"
    lifetime_sec: "{{ item['lifetime_sec'] | default(omit) }}"
    commit: "{{ item['commit'] | default('false') }}"
  with_items: "{{ cm_panos_ike_profile }}"
  when: "cm_panos_ike_profile is defined"

- name: "SET FACT TO MERGE THE DEFAULTS WITH THE FOUND VARIABLES"
  set_fact:
    cm_panos_ike_gateway: "{{ cm_panos_ike_gateway1 | collate_filter(tfstate, ansible_host) }}"
  when: "cm_panos_ike_gateway1 is defined"

- name: ADD IKE Gateway to Firewall
  panos_ike_gateway:
    ip_address: "{{ ansible_host }}"
    username: '{{ username }}'
    password: '{{ password }}'
    state: "{{ item['state'] | default('present') }}"
    name: "{{ item['name'] }}"
    protocol_version: "{{ item['protocol_version'] | default('ikev2') }}"
    interface: "{{ item['interface'] | default('ethernet1/1') }}"
    passive_mode: "{{ item['passive_mode'] | default(True) }}"
    liveness_check: "{{ item['liveness_check'] | default(omit)}}"
    peer_ip_value: "{{ item['public_ip'] }}"
    psk: "{{ item['tunnel_psk'] }}"
    crypto_profile_name: "{{ item['crypto_profile_name'] | default(omit) }}"
    local_ip_address_type: "{{ item['local_ip_address_type'] | default(omit) }}"
    local_ip_address: "{{ item['local_ip_address'] | default(omit) }}"
    nat_traversal: "{{ item['nat_traversal'] | default(False) }}"
    fragmentation: "{{ item['fragmentation'] | default(False) }}"
    dead_peer_detection: "{{ item['dead_peer_detection'] | default(False) }}"
    dead_peer_detection_interval: "{{ item['dead_peer_detection_interval'] | default(60) }}"
    dead_peer_detection_retry: "{{ item['dead_peer_detection_retry'] | default(10) }}"
    ikev1_exchange_mode: "{{ item['ikev1_exchange_mode'] | default('main') }}"
  with_items: "{{ cm_panos_ike_gateway }}"
  when: "cm_panos_ike_gateway1 is defined"
#- name: ADD IKE Gateway to Firewall
#  include_tasks: ike_gateway.yml
#  with_items: "{{ cm_panos_ike_gateway }}"
#  loop_control:
#    loop_var: "cm_panosike_item"
#  when: "cm_panos_ike_gateway is defined"

- name: "SET FACT TO MERGE THE DEFAULTS WITH THE FOUND VARIABLES"
  set_fact:
    cm_panos_spoke_tunnel: "{{ cm_panos_spoke_tunnel1 | collate_filter(tfstate, ansible_host) }}"
  when: "cm_panos_spoke_tunnel1 is defined"

- name: ADD Tunnel Interface
  panos_tunnel_int:
    ip_address: '{{ ansible_host }}'
    username: '{{ username }}'
    password: '{{ password }}'
    state: "{{ item['state'] | default('present') }}"
    if_name: "{{ item['if_name'] | default(omit) }}"
    ip: "{{ item['fw_tunnel_ip'] | default(omit) }}"
    zone_name: "{{ item['zone'] | default(omit) }}"
    vr_name: "{{ item['vr_name'] | default(omit) }}"
  with_items: "{{ cm_panos_spoke_tunnel }}"
  when: "cm_panos_spoke_tunnel1 is defined"

#- name: "MERGE LIST ITEMS"
#  set_fact:
#    lists_merged: "{{ cm_panos_ipsec_tunnel1 + cm_panos_ike_gateway1 + cm_panos_spoke_tunnel1 }}"
#
#
#- name: "SET FACT TO MERGE THE DEFAULTS WITH THE FOUND VARIABLES"
#  set_fact:
#    cm_panos_ipsec_tunnel: "{{ lists_merged | merge_tunnel_info( tfstate, ansible_host) }}"
#  when: "cm_panos_spoke_tunnel1 is defined"
#
#- name: Add IPSEC Tunnel to the firewall
#  panos_ipsec_tunnel:
#    ip_address: '{{ ansible_host }}'
#    username: '{{ username }}'
#    password: '{{ password }}'
#    state: "{{ item['state'] | default('present') }}"
#    name: "{{ item['spoke_name'] }}"
#    tunnel_interface: "{{ item['if_name'] | default(omit) }}"
#    ike_gtw_name: "{{ item['name'] }}"
#    ipsec_profile: "{{ item['ipsec_profile'] | default(omit) }}"
#    commit: "{{ item['commit'] | default('false') }}"
#  with_items: "{{ cm_panos_ipsec_tunnel }}"
#  when: "cm_panos_ipsec_tunnel1 is defined"